using FalkForge;
using FalkForge.Compiler.Msi;
using FalkForge.Localization;
using FalkForge.Models;

// An installer that packages another project's build output WITHOUT a
// hardcoded bin/ path.
//
// The file path below comes from ProjectOutputs.DemoApp, a compile-time
// constant generated by the FalkForge SDK (see obj/ProjectOutputs.g.cs). The
// SDK derives the member name from the referenced project's name (DemoApp) and
// fills in the resolved artifact path ($(TargetPath) for a CustomAction
// output type) at build time. If the app's output path changes, this installer
// follows automatically — nothing here is hardcoded.
return Installer.Build(args, package =>
{
    package.Name = "Project References Demo";
    package.Manufacturer = "Demo";
    package.Version = new Version(1, 0, 0);

    package.UseDialogSet(MsiDialogSet.Minimal);

    package.Localization(loc => loc
        .AddBuiltInCultures()
        .DefaultCulture("en-US")
        .DetectCulture());

    package.MediaTemplate(mt =>
    {
        mt.CabinetTemplate("data{0}.cab");
        mt.CompressionLevel(CompressionLevel.High);
        mt.EmbedCabinet(true);
    });

    // ProjectOutputs.DemoApp is the generated const holding the absolute path
    // to DemoApp.exe. No "../app/bin/Debug/..." anywhere.
    package.Files(files => files
        .Add(ProjectOutputs.DemoApp)
        .To(KnownFolder.ProgramFiles / "DemoApp"));
}, new MsiCompiler());
