using FalkForge;
using FalkForge.Compiler.Msi;
using FalkForge.Localization;
using FalkForge.Models;

// An installer that packages another project's WHOLE build output directory
// WITHOUT a hardcoded bin/ path.
//
// ProjectOutputs.DemoApp is a compile-time constant generated by the FalkForge
// SDK (see obj/ProjectOutputs.g.cs). The SDK derives the member name from the
// referenced project's name (DemoApp) and fills in the resolved artifact path
// ($(TargetPath) for a CustomAction output type) at build time. We derive the
// output directory from that constant and harvest every file in it via
// FromDirectory, so the entire app output (exe + dll + runtimeconfig + deps)
// is packaged — still with no hardcoded path anywhere.
return Installer.Build(args, package =>
{
    package.Name = "Project References Demo";
    package.Manufacturer = "Demo";
    package.Version = new Version(1, 0, 0);

    package.UseDialogSet(MsiDialogSet.Minimal);

    package.Localization(loc => loc
        .AddBuiltInCultures()
        .DefaultCulture("en-US")
        .DetectCulture());

    package.MediaTemplate(mt =>
    {
        mt.CabinetTemplate("data{0}.cab");
        mt.CompressionLevel(CompressionLevel.High);
        mt.EmbedCabinet(true);
    });

    // ProjectOutputs.DemoApp is a compile-time constant holding the RESOLVED
    // path to the app's primary output (DemoApp.dll) — no hardcoded bin/ path.
    // Deriving its directory and harvesting it packages EVERYTHING the app
    // builds (exe + dll + runtimeconfig.json + deps.json), still with no
    // hardcoded path: the directory follows the resolved artifact path.
    var appOutputDir = Path.GetDirectoryName(ProjectOutputs.DemoApp)!;
    package.Files(files => files
        .FromDirectory(appOutputDir)
        .To(KnownFolder.ProgramFiles / "DemoApp"));

    // Alternative: package just the single resolved artifact.
    // package.Files(files => files
    //     .Add(ProjectOutputs.DemoApp)
    //     .To(KnownFolder.ProgramFiles / "DemoApp"));
}, new MsiCompiler());
