using System.Text.Json.Serialization;
using FalkForge.Engine.Protocol.Manifest;

namespace FalkForge.Compiler.Bundle.Compilation;

[JsonSerializable(typeof(InstallerManifest))]
[JsonSerializable(typeof(ManifestChainItem))]
[JsonSerializable(typeof(PackageManifestChainItem))]
[JsonSerializable(typeof(RollbackBoundaryManifestChainItem))]
[JsonSerializable(typeof(PackageInfo))]
[JsonSerializable(typeof(PackageType))]
[JsonSerializable(typeof(InstallScope))]
[JsonSerializable(typeof(RelatedBundleEntry))]
[JsonSerializable(typeof(RelatedBundleRelation))]
[JsonSerializable(typeof(ManifestVariable))]
[JsonSerializable(typeof(ManifestVariable[]))]
[JsonSerializable(typeof(ManifestFeature))]
[JsonSerializable(typeof(ManifestFeature[]))]
[JsonSerializable(typeof(ManifestDependencyProvider))]
[JsonSerializable(typeof(ManifestDependencyProvider[]))]
[JsonSerializable(typeof(ManifestDependencyConsumer))]
[JsonSerializable(typeof(ManifestDependencyConsumer[]))]
[JsonSerializable(typeof(ManifestDependencyRequirement))]
[JsonSerializable(typeof(ManifestDependencyRequirement[]))]
[JsonSerializable(typeof(ManifestUpdateFeed))]
[JsonSerializable(typeof(UpdatePolicy))]
[JsonSerializable(typeof(ManifestDryRunAction))]
[JsonSerializable(typeof(ManifestDryRunAction[]))]
[JsonSerializable(typeof(string[]))]
[JsonSerializable(typeof(PreUIPackageInfo))]
[JsonSerializable(typeof(PreUIPackageInfo[]))]
[JsonSerializable(typeof(PreUIRebootBehavior))]
[JsonSerializable(typeof(PreUIPayloadMode))]
[JsonSerializable(typeof(ExternalContainerInfo))]
[JsonSerializable(typeof(ExternalContainerInfo[]))]
internal partial class ManifestJsonContext : JsonSerializerContext;
