using FalkForge.Compiler.Msi.Recipe;
using Xunit;

namespace FalkForge.Compiler.Msi.Tests.Recipe;

public sealed class SummaryInfoRecipeTests
{
    [Fact]
    public void Construct_with_all_fields_succeeds()
    {
        SummaryInfoRecipe recipe = new()
        {
            Title = "Installation Database",
            Subject = "FalkForge Demo",
            Author = "Acme Inc.",
            Template = "x64;1033",
            Keywords = "Installer",
            Comments = "Generated by FalkForge",
            RevisionNumber = "{AAAAAAAA-BBBB-CCCC-DDDD-EEEEEEEEEEEE}",
            CodePage = 1252,
            CreatingApplication = "FalkForge",
            WordCount = 2,
            PageCount = 200,
            Security = 2,
        };

        Assert.Equal("Installation Database", recipe.Title);
        Assert.Equal("FalkForge Demo", recipe.Subject);
        Assert.Equal("Acme Inc.", recipe.Author);
        Assert.Equal("x64;1033", recipe.Template);
        Assert.Equal("Installer", recipe.Keywords);
        Assert.Equal("Generated by FalkForge", recipe.Comments);
        Assert.Equal("{AAAAAAAA-BBBB-CCCC-DDDD-EEEEEEEEEEEE}", recipe.RevisionNumber);
        Assert.Equal(1252, recipe.CodePage);
        Assert.Equal("FalkForge", recipe.CreatingApplication);
        Assert.Equal(2, recipe.WordCount);
        Assert.Equal(200, recipe.PageCount);
        Assert.Equal(2, recipe.Security);
    }

    [Fact]
    public void Equal_recipes_compare_equal()
    {
        SummaryInfoRecipe a = new()
        {
            Title = "T",
            Subject = "S",
            Author = "A",
            Template = "x64;1033",
            Keywords = "K",
            Comments = "C",
            RevisionNumber = "{00000000-0000-0000-0000-000000000001}",
            CodePage = 1252,
            CreatingApplication = "FalkForge",
            WordCount = 2,
            PageCount = 200,
            Security = 2,
        };
        SummaryInfoRecipe b = new()
        {
            Title = "T",
            Subject = "S",
            Author = "A",
            Template = "x64;1033",
            Keywords = "K",
            Comments = "C",
            RevisionNumber = "{00000000-0000-0000-0000-000000000001}",
            CodePage = 1252,
            CreatingApplication = "FalkForge",
            WordCount = 2,
            PageCount = 200,
            Security = 2,
        };

        Assert.Equal(a, b);
    }
}
