using FalkForge.Compiler.Msi.Recipe;
using Xunit;

namespace FalkForge.Compiler.Msi.Tests.Recipe;

public sealed class SummaryInfoRecipeTests
{
    [Fact]
    public void Construct_with_all_fields_succeeds()
    {
        SummaryInfoRecipe recipe = new()
        {
            Title = "Installation Database",
            Subject = "FalkForge Demo",
            Author = "Acme Inc.",
            Template = ";1033",
            Keywords = "Installer",
            Comments = "Generated by FalkForge",
            RevisionNumber = 200,
            CodePage = 1252
        };

        Assert.Equal("Installation Database", recipe.Title);
        Assert.Equal("FalkForge Demo", recipe.Subject);
        Assert.Equal("Acme Inc.", recipe.Author);
        Assert.Equal(";1033", recipe.Template);
        Assert.Equal("Installer", recipe.Keywords);
        Assert.Equal("Generated by FalkForge", recipe.Comments);
        Assert.Equal(200, recipe.RevisionNumber);
        Assert.Equal(1252, recipe.CodePage);
    }

    [Fact]
    public void Equal_recipes_compare_equal()
    {
        SummaryInfoRecipe a = new()
        {
            Title = "T",
            Subject = "S",
            Author = "A",
            Template = ";0",
            Keywords = "K",
            Comments = "C",
            RevisionNumber = 1,
            CodePage = 1252
        };
        SummaryInfoRecipe b = new()
        {
            Title = "T",
            Subject = "S",
            Author = "A",
            Template = ";0",
            Keywords = "K",
            Comments = "C",
            RevisionNumber = 1,
            CodePage = 1252
        };

        Assert.Equal(a, b);
    }
}
