namespace FalkForge.Engine.Protocol.Messages;

/// <summary>
/// Sent from the Engine to the Elevation companion immediately after the HMAC
/// handshake completes. Carries the session correlation id so that log entries
/// written by the elevation process can be matched against engine and UI logs
/// for the same install session.
/// </summary>
/// <remarks>
/// Wire direction: Engine → Elevated (<see cref="MessageType.SessionStart"/> = 0x0302).
/// The elevated process treats this message as a one-time session initialiser and
/// passes the id to <c>ElevationSecurityLog.SetCorrelationId</c>.
/// </remarks>
public sealed class SessionStartMessage : EngineMessage
{
    public override MessageType Type => MessageType.SessionStart;

    /// <summary>
    /// The session-wide correlation id generated by the engine at session start.
    /// All log entries from the UI, Engine, and Elevation processes that belong
    /// to the same install session carry this id.
    /// </summary>
    public Guid CorrelationId { get; init; }

    /// <summary>
    /// UTC timestamp at which the install session started (engine side).
    /// Informational; not used for correlation — the <see cref="CorrelationId"/> is
    /// the primary cross-process key.
    /// </summary>
    public DateTimeOffset StartedUtc { get; init; }
}
